### ISSUE TITLE
Frequent stutters occur when using Fresh Animations

### ISSUE THREAD

**Issue by Tenuuu** [Estecka/mc-Shifting-Wares#12] opened 2024-07-04 21:12 UTC
When using the mod alongside Fresh Animations, looking at villagers causes the game to experience frequent frame stutters

**Comment by Estecka** [comment] 2024-07-04 22:03
That is extremely weird. Shifting-wares has absolutely nothing to do with rendering, yet I am able to reproduce this.

The only hunch I have is that either EMF or ETF is continuously regenerating the villagers NBT data. If that is indeed the case I don't know what I could possibly do; that logic _isn't supposed_ to be called all the time.

**Comment by Estecka** [comment] 2024-07-04 22:44
Good news, this was much less scary to fix than I feared. There'll be a fix up soon.

This is indeed caused by EMF constantly serializing the villagers, but all I needed was disable my own serialization logic on the render thread.

One thing that still bothers me is that this code should have thrown errors when called on the render thread, errors which were notoriously _missing_ from the log. I suspect EMF is silencing these errors, which is a bit bad as seeing them would have enabled me to notice this issue much sooner. If you hadn't reported this, I might have never suspected that SW could cause such performance issues.

**Comment by Estecka** [comment] 2024-07-04 23:47
Fixed in v2.1.2 and v2.2.2

**Closed as completed by Estecka** 2024-07-04 23:47 UTC
Labels: compatibility

**Comment by Tenuuu** [comment] 2024-07-05 00:45
Thank you so much for the quick fix! Great mod by the way! :D

**Comment by Estecka** [comment] 2024-07-05 13:49
I forgot to mention: when investigating this, I found an option in EMF's menu, that controls how often it computes a mob's NBT data. I don't think Fresh Animation makes any use of this data (to be confirmed), so disabling this option completely should further increase performances at no visual cost.

In EMF, this option is found under Models -> Performance Settings -> Model Update Rate
